### ISSUE TITLE
Description mentions there is no server.

### ISSUE THREAD

**Issue by phcerdan** [Kitware/web-project-templates#10]
Hi @jourdain, thanks for maintaining these templates.

I am just starting to explore the vtk.js + paraview server.

> This project aims to provide a base template in the creation of a Web project involving vtk.js without rendering server.

Is that description still accurate for these templates? I understand that there is an option for also have a server side (with pure VTK or ParaView). You explained more accurately here: https://discourse.vtk.org/t/confusion-with-tool-selection-vtk-vs-paraview-for-web-based-volume-rendering-of-large-data-sets/1384/3

**Comment by jourdain** [comment]
- vue-vtkjs-pvw-template
  - This aims to use either VTK or ParaView to do remote rendering 
- vue-vtkjs-template
  - This aims to be just client side

**Comment by phcerdan** [comment]
Makes sense, then the Readme of `vue-vtkjs-pvw-template` should be updated.

![image](https://user-images.githubusercontent.com/3021667/108379115-e8bc7580-7205-11eb-9125-04b0f0d2dfef.png)

**Comment by jourdain** [comment]
Yes, it was probably a copy-paste from the vtk.js one who was first... Since both apps "are the same" in term of rendering and UI, but not on the backend side of things.

**Comment by jourdain** [comment]
Thanks for pointing it out. I just did some edits.

**Comment by jourdain** [comment]
You should pull again, we just did a cleanup pass to remove all the noise and leave only the good practices...

**Comment by phcerdan** [comment]
Thanks @jourdain and @DrewLazzeriKitware, it helps!
