### ISSUE TITLE
Will there be a performance difference between using VTK and Paraview as the server?

### ISSUE THREAD

**Issue by Recope** [Kitware/web-project-templates#17]
When I have many objects, I find that Paraview performs poorly, with only 10 fps. Is it because the ParaView object is heavy? Is there an improvement with VTK as server?

**Comment by jourdain** [comment]
The best way to go about that is to use composite dataset with fewer actors/representation. Also I'm not sure you would see much more speed improvement with VTK. But I guess it really depend on what are your many objects...

**Comment by jourdain** [comment]
Did you set `view.EnableRenderOnInteraction = 0` on your ParaView view?

**Comment by Recope** [comment]
yes, I set this on the server side: 
    simple.GetRenderView().EnableRenderOnInteraction = 0

**Comment by jourdain** [comment]
Hard to tell without seeing the problem. Maybe the GPU is not detected properly?

**Comment by jourdain** [comment]
The performances should be very similar
