### ISSUE TITLE
can't run python serve

### ISSUE THREAD

**Issue by lgq00139** [Kitware/web-project-templates#29]
Hello,I want to ask how to run this python serve .
Any help would be appreciated.

**Comment by jourdain** [comment]
https://github.com/Kitware/web-project-templates/tree/master/vue-vtkjs-pvw-template#run-the-application

**Comment by lgq00139** [comment]
Sorry it's me again,when i run the vtkw-server:

--ModuleNotFoundError: No module named 'vtk.web'. --

I don't know how to use this module,Can you help me?Thank you so much
