### ISSUE TITLE
The returned image can be seen on the console, but it cannot be displayed in the browser

### ISSUE THREAD

**Issue by RQsky** [Kitware/web-project-templates#30]
Hello, I have a very strange question, I think it is relatively simple for you, but I can't start.
I almost completely use this demo in my project, wanting to implement a remote rendering model. I can be sure that I have succeeded functionally, I mean I can see the returned image in the console. But I can't see the returned image in the window, I don't know why, I hope you can help me.
My project address is: `https://github.com/RQsky/dydy`
You can enter: `npm run dev` to run it
To make it easy for you to quickly view, I modified the project entry, it is now `src/components/map-router/obj.vue`
In addition, there are files related to remote rendering: `src/components/map-router/widgets/RemoteRenderingView.vue`
And `protocols/`, `store/`,
Thank you very much.

**Comment by jourdain** [comment]
If you use remote rendering, I don't see the server part in your repo

**Comment by RQsky** [comment]
Hello, because my web can receive the information returned by the server, I think it is not a problem with the server, so I did not upload the server code. For your convenience, I just uploaded the server-side code. In order to make it run correctly, you may need to modify the model path `cone = simple.PLYReader(FileNames = "F:\\test\\app\\server\\pvpython\\asserts\\VLX-face.ply")` to the correct path on your computer.

**Comment by RQsky** [comment]
The problem was solved, I completely copied your view-related code, and then it was completely fine. Although I don't know what the problem is, I think I will figure it out if I have time in the future. Thank you.
