### ISSUE TITLE
Deploy the model server in production

### ISSUE THREAD

**Issue by RQsky** [Kitware/web-project-templates#49]
Hello, I have successfully run the demo on my computer. But I want to deploy the server part on the server, I am completely new to this, so I have some problems.
On my computer I have to start the server every time with the following command:
`$ /.../pvpython ./server/pvpython/pvw-server.py --port 1234`

For deployment, I came up with the following approach:
Our remote model is only a small part of the project, and our project has a java backend. I plan to write a java interface. Every time it is requested, the above shell will be started to start the model, and then the front end will establish a websocket connection with the model.

Don't know if it's possible, hope to get your advice.

**Comment by jourdain** [comment]
Hi this is definitely possible as this is the model described [here for multi-user setup](http://kitware.github.io/paraviewweb/docs/multi_user_setup.html).

We created a simple implementation of a [launcher](https://github.com/Kitware/wslink/blob/master/python/src/wslink/launcher.py) to run a vtk/pv web process and return connection information (sessionURL). On your end, you can create something similar within your Java backend.

Also on top of that we created several docker images [1](http://kitware.github.io/paraviewweb/docs/docker.html) [2](https://hub.docker.com/r/kitware/trame) that bundle apache for the routing along with the launcher and what ever vtk/pv web app. 

For local experiment, of the launcher, the easiest part might be [with trame with that example](https://github.com/Kitware/trame/tree/master/examples/validation/launcher). Then transpose it to the template example.
