### ISSUE TITLE
start 'server' on remote server

### ISSUE THREAD

**Issue by RQsky** [Kitware/web-project-templates#50]
1. I copied the files from the `vue-vtkjs-pvw-template/server/pvpython/` directory to my server and ran the following commands:
` pvpython ../../pvw-server.py --port 1234 `
the output is:
![image](https://user-images.githubusercontent.com/36152827/170828823-12e31926-1c27-4ec9-a504-ad6e4a507471.png)
2. I set ` config.sessionURL = `ws://${my_server_hostname}:1234/ws` ` in the client，and start it but get the following result:
![image](https://user-images.githubusercontent.com/36152827/170828923-ce4afb01-e3e4-4969-8694-877d6f2420ed.png)
3. It seems that my server is not started. I don't understand it very much, and I don't know how to debug it. I hope to get your help.
4. I can ping the server.

**Comment by jourdain** [comment]
You probably need to add `--host 0.0.0.0` to allow external connection to your process.

**Comment by RQsky** [comment]
Thanks a lot for your reply, it worked. Sorry I don't know much about linux and network.
But then I encountered a new problem. I checked the information and found that everyone may encounter similar problems when compiling paraview, but I have not found a feasible detailed solution, so I still want to ask you.
![1653811979](https://user-images.githubusercontent.com/36152827/170858735-de90ff7b-4587-485f-b9ab-2d303754c022.jpg)
![1653811979(1)](https://user-images.githubusercontent.com/36152827/170858736-b4a36875-6622-4242-a08c-1e8597d6dc52.jpg)

**Comment by jourdain** [comment]
If you don't have X, you are using the wrong ParaView binary. You need to use the EGL one.

**Comment by RQsky** [comment]
I don't know what is X and what is EGL. My Paraview is [https://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.10&type=binary&os=Linux&downloadFile=ParaView-5.10.0-MPI-Linux-Python3.9-x86_64.tar.gz](url)

**Comment by jourdain** [comment]
Do you have a graphical environment on your linux box? If not you need to go [Headless](https://www.paraview.org/download/?version=nightly&filter=Linux&tags=OFFSCREEN)

**Comment by RQsky** [comment]
Wow, I get it. I have not a graphical environment on my linux box. Thank you so much!

**Comment by RQsky** [comment]
Sorry to bother you again, I installed the package in Figure 1, but I encountered the problem in Figure 2 when I ran it. Is it because I am missing any dependencies?
![1653891605(1)](https://user-images.githubusercontent.com/36152827/170929291-7a191f3e-8b54-4faa-b41c-bbf22118e0aa.png)
![image](https://user-images.githubusercontent.com/36152827/170929332-f5abe87c-86bb-4ce9-b7a9-0d1bb0c449a7.png)

**Comment by jourdain** [comment]
This is indeed strange, `pvpython` should have `wslink` within its dependencies.

**Comment by jourdain** [comment]
The next nightly should be fixed and have the missing wslink dependency. Thanks for reporting the issue.

**Comment by RQsky** [comment]
> Do you have a graphical environment on your linux box? If not you need to go [Headless](https://www.paraview.org/download/?version=nightly&filter=Linux&tags=OFFSCREEN)

Hello, what I downloaded earlier is from the link you provided here:
[ParaView-master-5.10.1-1287-g8b2e53ee04-egl-MPI-Linux-Python3.9-x86_64.tar.gz](https://www.paraview.org/paraview-downloads/download.php?submit=Download&version=nightly&type=binary&os=Linux&downloadFile=ParaView-master-5.10.1-1287-g8b2e53ee04-egl-MPI-Linux-Python3.9-x86_64.tar.gz)
然后出现了上述问题。

Just now, I used:
[ParaView-5.10.0-egl-MPI-Linux-Python3.9-x86_64.tar.gz](https://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.10&type=binary&os=Linux&downloadFile=ParaView-5.10.0-egl-MPI-Linux-Python3.9-x86_64.tar.gz)

It worked!
I already have access to my model, thank you so much!

**Comment by RQsky** [comment]
I'm very sorry, but I have a new problem.
I debug in development environment and everything works fine. But when I package the front-end project `npm run build` and deploy it to the server.
While viewing the model, I am getting an error like below.
![image](https://user-images.githubusercontent.com/36152827/171394799-2a95f260-6543-4ddf-be46-6538cf1bdc5b.png)

I'm wondering why I don't see this error in the development environment, I also checked some information, but couldn't find a solution. So I would like to ask you the reasons and solutions.

**Comment by jourdain** [comment]
From your stack it is hard to tell. But looking at the network tab and seeing how your server respond and with what content would definitely help. Do you use a launcher? Is your sessionURL correct?

**Comment by jourdain** [comment]
Right, I forgot about your Java backend. Do you have some load-balancer or proxy that needs to properly forward/handle the websocket?

**Comment by RQsky** [comment]
I have not. I just don't understand why the same code, everything works fine in the development environment, but an error is reported when it is packaged into the production environment. I checked the client code and changed all const-defined variables to let-defined, to no avail.

**Comment by jourdain** [comment]
Do you have a browser caching issue from old code? I don't see why it would not work on prod environment either. 
With our launcher we write the stdout to disk. It might be good to see the error on the server if any.

Also do you have all the GPU driver and so on, on your prod server? 

Try running that pvw-server.py command line by hand on your prod server to see if something break there vs local for dev.

**Comment by RQsky** [comment]
错误还未得到解决，不过我排除了服务端的问题。

**Comment by RQsky** [comment]
The error has not been resolved, but I ruled out a server-side problem. Because when I didn't start the server, the front end still reported this error instead of connection error.
I will continue to work hard to solve this problem.
thanks for your help.
