### ISSUE TITLE
Module parse failed: Unexpected token ...

### ISSUE THREAD

**Issue by RQsky** [Kitware/web-project-templates#53]
![image](https://user-images.githubusercontent.com/36152827/172003430-b6e31f05-2d5a-484e-9979-b7103cc9f6f9.png)

Sorry to bother you again, why does the js file of the vtk.js module need to be parsed by the loader? How can I configure it.
I modified it on the basis of this project, and I can successfully load my model in the production environment, but it fails in our project. So I speculate that it is a problem with the version of dependencies. So I updated the dependencies so that they are almost the same as the dependencies of this project. 
The original dependencies are as follows:
![278ffad42b326995c74f165cda9c441](https://user-images.githubusercontent.com/36152827/172003871-f202d244-d031-4d19-b736-ef8b129b410e.png)

The latest dependencies are as follows:
![image](https://user-images.githubusercontent.com/36152827/172003917-5adb276a-6f9f-4958-a044-0c6a45fe5fdd.png)

But I ran into the top problem.

**Comment by jourdain** [comment]
Yes it make sense `vtk.js` and `@kitware/vtk.js` are NOT the same bundles. The `@kitware/vtk.js` is the ESM one while `vtk.js` is the umd/common/source one.

I you do not want to use a loader to transpile vtk.js code base, you must use the ESM one and make sure you import the various vtk.js classes accordingly in your code. Please read that [document](https://kitware.github.io/vtk-js/docs/intro_vtk_as_es6_dependency.html) for more details.

**Comment by RQsky** [comment]
I suspect that my use of `@kitware/vtk.js` is causing the production failures.
So I decided to use `vtk.js` .
Should this require `shader-loader` and `worker-loader`?
And I use `webpack` . 
How can I configure them?

**Comment by jourdain** [comment]
yes `vtk.js` require you to transpile the code especially if you import the classes from the `vtk.js/Source/**`

**Comment by jourdain** [comment]
Just read that [guide](https://kitware.github.io/vtk-js/docs/old_intro_vtk_es6.html)

**Comment by RQsky** [comment]
Thank you! I'll take a look tomorrow.

**Comment by RQsky** [comment]
It's not because I use `@kitware/vtk.js` instead of `vtk.js` to cause this problem, the real reason is that my `webpack` version is too low (v3.6), when I use `vue-cli-service` to package the project, this problem has been solved. I'm guessing that using `webpack 4.0+` should also solve this problem.
