### ISSUE TITLE
Error when starting paraview server on windows server

### ISSUE THREAD

**Issue by RQsky** [Kitware/web-project-templates#54]
![image](https://user-images.githubusercontent.com/36152827/173182569-5643e24f-0fa1-478c-865f-a5f3a59bc9d0.png)

The mainstream argument is the problem of environment variables or the problem of the graphics card driver.
My environment variables are as shown below, which is the same as the configuration of another Windows server (TITAN graphics card), but the other one does not report an error.
![image](https://user-images.githubusercontent.com/36152827/173182928-7eebd981-7382-4bf5-8572-ac866b19ec8b.png)

The server that reported the error uses NVIDIA A40 graphics card and drives v31. I went back to v30.0.14.7111 and it didn't solve the problem.

So I want to ask you how to deal with this problem, I'm at a loss.

**Comment by jourdain** [comment]
If I'm not mistaken the A40 is headless and does not implement OpenGL rendering. If that is the case, it might support EGL and if it does you will to have to download the EGL build of ParaView for linux.

**Comment by RQsky** [comment]
But the server is installed with `Windows` operating system, `paraview` for `Linux` should not be available.
Can I add any parameters when starting the model so that the server uses the `CPU` to render the model. What should I do?

**Comment by jourdain** [comment]
Without further details it is hard to help. But if you want a personalized support to go to the bottom of your issue, [we can help](https://www.kitware.com/contact/).

**Comment by RQsky** [comment]
Thank you very much for your continued help. The problem is solved.
The reason is that `windows docker desktop` has resource restrictions on containers. So rendering a `187MB ply` file will cause the subprocess to crash and exit, and rendering fails.
When I unblock docker restrictions, everything is OK.

**Comment by jourdain** [comment]
Great, thanks for reporting back and providing the reason of the issue you were running into, that can definitely help other running into the same limitation.
