### ISSUE TITLE
Migration to Vue3

### ISSUE THREAD

**Issue by JulienChampagnol** [Kitware/web-project-templates#77]
These examples are great but not updated to Vue3 and Vuetify3. Do you plan on upgrading them? Are there other examples using vtk web workflow available in Vue3?

**Comment by jourdain** [comment]
Not that I know of. Also those are meant to teach how you can integrate the vtk.js plain JS library into the vue framework. 
Once you understand the gist, you should be able to map to your project regardless of the vue version. 

What would be fundamentally different with vue3?

**Comment by JulienChampagnol** [comment]
We are having trouble with the resizing of the canvas and we thought it was about the vue3 migration.

**Comment by JulienChampagnol** [comment]
We are having trouble with the resizing of the canvas and we thought it was about the vue3 migration.
We will investigate further, thanks for your answer!

**Comment by jourdain** [comment]
You just need to trigger the `openglRenderWindon.setSize(width, height)` based on the real Vue component size.
